CREATE TABLE teams (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE users (
    id INT(11) NOT NULL AUTO_INCREMENT,
    teamId INT(11) NOT NULL,
    role VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
    email VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
    password VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (teamId) REFERENCES teams (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE challenges (
    id INT(11) NOT NULL AUTO_INCREMENT,
    project VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
    title VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
    points INT(11) NOT NULL,
    topic VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
    build_call VARCHAR(255) COLLATE utf8_unicode_ci NOT NULL,
    description VARCHAR(512) COLLATE utf8_unicode_ci DEFAULT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE user_challenges (
    userId INT(11) NOT NULL,
    challlengeId INT(11) NOT NULL,
    downloadPath VARCHAR(512) COLLATE utf8_unicode_ci DEFAULT NULL,
    challengeResult VARCHAR(512) COLLATE utf8_unicode_ci DEFAULT NULL,
    solved tinyint(1) DEFAULT 0,
    status VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT "pending",
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (userId, challlengeId),
    FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (challlengeId) REFERENCES challenges (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE hardware_keys (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) COLLATE utf8_unicode_ci NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE challenge_keys (
    keyId INT(11) NOT NULL,
    challengeId INT(11) NOT NULL,
    keyOrder INT(11) NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (keyId, challengeId),
    FOREIGN KEY (keyId) REFERENCES hardware_keys (id) ON DELETE CASCADE,
    FOREIGN KEY (challengeId) REFERENCES challenges (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE user_keys (
    keyId INT(11) NOT NULL,
    userId INT(11) NOT NULL,
    keyValue VARCHAR(512) COLLATE utf8_unicode_ci DEFAULT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (keyId, userId),
    FOREIGN KEY (keyId) REFERENCES hardware_keys (id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

